services:
  backend:
    build:
      context: ./backend
    profiles:
      - ""  # Default profile (always active)
      - development
      - production
    ports:
      - "${API_PORT:-8101}:${API_CONTAINER_PORT:-8000}"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      # Updated to use containerized Ollama
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      chromadb:
        condition: service_started
      ollama:
        condition: service_healthy
    networks:
      - synapse-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

  chromadb:
    image: chromadb/chroma:latest
    container_name: synapse_chromadb
    profiles:
      - ""  # Default profile (always active)
      - development
      - production
    ports:
      - "${CHROMA_GATEWAY_PORT:-8102}:${CHROMA_CONTAINER_PORT:-8000}"
    env_file:
      - .env
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=${CHROMADB_ALLOW_RESET:-TRUE}  # Set to FALSE in production
    networks:
      - synapse-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M

  # NEW: Containerized Ollama service
  ollama:
    image: ollama/ollama:latest
    profiles:
      - ""  # Default profile (always active)
      - development
      - production
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    networks:
      - synapse-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 1G

  # Debug service for troubleshooting
  debug:
    image: nicolaka/netshoot:latest
    profiles:
      - debug
    command: tail -f /dev/null
    networks:
      - synapse-network
    depends_on:
      - backend
      - chromadb
      - ollama

volumes:
  chroma_data:
  ollama_data:  # NEW: Persistent storage for Ollama models

networks:
  synapse-network:
    driver: bridge