services:
  backend:
    build:
      context: ./backend
    profiles:
      - ""  # Default profile (always active)
      - development
      - production
    ports:
      - "${API_PORT:-8101}:${API_CONTAINER_PORT:-8000}"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      # Updated to use containerized Ollama
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      chromadb:
        condition: service_healthy
      ollama:
        condition: service_healthy
    networks:
      - synapse-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

  chromadb:
    image: chromadb/chroma:0.4.24
    container_name: synapse_chromadb
    profiles:
      - ""
      - development
      - production
    ports:
      - "${CHROMA_GATEWAY_PORT:-8102}:${CHROMA_CONTAINER_PORT:-8000}"
    env_file:
      - .env
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=${CHROMADB_ALLOW_RESET:-TRUE}
      - ANONYMIZED_TELEMETRY=FALSE
    networks:
      - synapse-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/api/v1')"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 120s  

  ollama:
    image: ollama/ollama:latest
    container_name: synapse_ollama
    profiles:
      - ""
      - development
      - production
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - synapse-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "ollama list || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '1'
          memory: 2G

  # Debug service for troubleshooting
  debug:
    image: nicolaka/netshoot:latest
    profiles:
      - debug
    command: tail -f /dev/null
    networks:
      - synapse-network
    depends_on:
      - backend
      - chromadb
      - ollama

volumes:
  chroma_data:
  ollama_data:  # NEW: Persistent storage for Ollama models

networks:
  synapse-network:
    driver: bridge